-- DROP TABLE vs_file_mapping;
CREATE TABLE APEX_APP.vs_file_mapping (
    id NUMBER GENERATED by default on null as IDENTITY,
    path varchar2(1024),    
    original_resource_name varchar2(1024) -- Original file that caused the event to trigger.
);
